### ISSUE TITLE
Tweet feed

### ISSUE THREAD

**Issue by ctrueden** [fiji/fiji.github.io#17]
A question for anyone who has opinions about https://fiji.sc, probably especially @fjug and @tomancak: what should we do about the Tweet feed in the right-hand column? I have been [led to believe](https://meta.discourse.org/t/bye-bye-embedded-tweet-previews/261708?u=curtis_rueden) that such embedded feeds may stop working at some point soon? And anyway, it seems with Twitter imploding, many people are not posting much anymore. The last `@FijiSc` post was October 2022. Do we want to start an equivalent Mastodon channel for Fiji, and embed that instead? Thoughts?

**Comment by fjug** [comment]
It is a good question I’m afraid I will not have a good answer for.
I assume that one of the most active posters for Fiji was likely me and recently I am on some sort of Twitter sabbatical.

Mastodon would be an option for sure, but the uptake is not as bombastic as I hoped.

Maybe let me suggest this: the moment embedded Twitter feed break (or whenever we decide to go Mastodon) I will be happy to help make such a Fiji Mastodon account exist and we can replace the broken (or unwanted) embedded Twitter feed disappear.

How does this sound?

Best,
Florian

From: Curtis Rueden ***@***.***>
Date: Wednesday, 3 May 2023 at 21:33
To: fiji/fiji.github.io ***@***.***>
Cc: Florian Jug ***@***.***>, Mention ***@***.***>
Subject: [fiji/fiji.github.io] Tweet feed (Issue #17)

A question for anyone who has opinions about https://fiji.sc, probably especially @fjug<https://github.com/fjug> and @tomancak<https://github.com/tomancak>: what should we do about the Tweet feed in the right-hand column? I have been led to believe<https://meta.discourse.org/t/bye-bye-embedded-tweet-previews/261708?u=curtis_rueden> that such embedded feeds may stop working at some point soon? And anyway, it seems with Twitter imploding, many people are not posting much anymore. The last @FijiSc post was October 2022. Do we want to start an equivalent Mastodon channel for Fiji, and embed that instead? Thoughts?

**Comment by ctrueden** [comment]
@fjug wrote:
> the moment embedded Twitter feed break (or whenever we decide to go Mastodon) I will be happy to help make such a Fiji Mastodon account exist and we can replace the broken (or unwanted) embedded Twitter feed disappear.

Sounds perfect! I will close this issue until such time as we notice the feed has failed. :+1:
