### ISSUE TITLE
Download link for linux is actually a macOS .app?

### ISSUE THREAD

**Issue by GiuliaFedrizzi** [fiji/fiji.github.io#18]
Sorry if this is not the correct place to file this.

I'm trying to download the Linux binaries for Fiji from [the Fiji website](https://fiji.sc/) but the .zip actually contains a MacOS .app file. 

I have tried multiple mirrors but always get the same result

Have I misunderstood something? I can't find any specific instructions on how to run the `Fiji.app`  on Linux.

**Comment by ctrueden** [comment]
The folder name is `Fiji.app` because Fiji is a portable application, intended to be launchable cross-platform. There should be an `ImageJ-linux64` executable inside though, which is what you should click to launch the program. :+1:
