### ISSUE TITLE
plugins.json is auto-redirecting to imagej.net

### ISSUE THREAD

**Issue by mattxwang** [fiji/fiji.github.io#4]
Hey @ctrueden ,

I was just taking a look at the website and noticed that the plugins card view is broken. Specifically, the HTTP request to `plugins.json` is being redirected to imagej.net, which is really strange. Is the web server configured to redirect requests to the top-level of the app to ImageJ? If needed, I can move `plugins.json` to the `site/` folder.

**Comment by ctrueden** [comment]
Thanks for noticing! With cf84d4cb830f26c3f6bd101b74ccd318db2ea0d5 I moved it into `site`. The broad redirect rule to imagej.net is for historical reasons, and I'd rather not mess with that side of things unless truly necessary.

There still seems to be something weird, though: `curl https://fiji.sc/site/plugins.json` works as expected, but accessing that URL from my browsers yields 404 from GitHub. I'll keep digging.

**Comment by mattxwang** [comment]
Hm, that's strange. For me, accessing `https://fiji.sc/site/plugins.json` works properly (with no 404) - have you hard-refreshed the page and deleted the cache if needed?

**Comment by ctrueden** [comment]
The stale `plugins.json` problem magically resolved itself after a while! Probably browser cache, yeah (although I tested with several browsers). `¯\_(ツ)_/¯`

I also added all the remaining plugins from the forum thread. All seems to be working well now! :+1:
