### ISSUE TITLE
Client OS not properly identified by javascript for download option.

### ISSUE THREAD

**Issue by turekg** [fiji/fiji.github.io#9]
In some cases (Firefox for Ubuntu Linux) the OS is not recognized and the user gets "Fiji is not currently supported on your OS" message.
A discussion of this problem can also be found on the forum at https://forum.image.sc/t/fiji-sc-website-greets-with-fiji-doesnt-currently-support-your-os-on-supported-os/26239.

**Comment by turekg** [comment]
The issue stems from the fact that the script employed to make the OS determination uses "navigator.appVersion" which often will contain OS info along with version information, but this is not guaranteed. A better approach is to use "navigator.userAgent". I will fix this and submit a pull request

**Comment by carandraug** [comment]
I'm having the same issue. The `appVersion` returns the version information of the browser and no information about the OS.

But whatever fix is done about this, I think the displayed message in case OS identification fails should also be changed. Currently, it says "Fiji doesn't currently support your OS". Instead, it should say something like "Failed to identify your OS" and maybe offer to download the no-JRE version.

**Comment by ctrueden** [comment]
> I think the displayed message in case OS identification fails should also be changed. 

@carandraug I agree. With 19b8e2444034bcdbd913ae08ec837a842d7f476f I changed it to this:

<img width="312" alt="Screen Shot 2019-09-10 at 10 20 59 " src="https://user-images.githubusercontent.com/556626/64627251-e620e400-d3b4-11e9-9a81-51aa34a181ee.png">

Still plenty of room for improvement, but at least user isn't given a needless failure message.

**Comment by carandraug** [comment]
"Choose a download" is much better. Thank you for fixing this.
